server:
  port: 8081
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:rasmoodb
    username: rasmoo
    password: rasmoo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true